name = "SigmaClip"
uuid = "e8e6a0c9-ed5e-482f-a5cb-ec074f5ee4bb"
version = "0.1.0"
authors = ["Matteo Sapori <matteosap@hotmail.com>"]

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Statistics = "1.11.1"
