name = "SigmaClip"
uuid = "e8e6a0c9-ed5e-482f-a5cb-ec074f5ee4bb"
version = "0.1.1"
authors = ["Matteo Sapori <matteosap@hotmail.com>"]

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Aqua = "0.8"
Statistics = "1.0"
Test = "1.0"
julia = "1.10"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Test"]
